CREATE TABLE IF NOT EXISTS warehouseTable(id serial PRIMARY KEY,  product_name text, description text, stock_lvl INT, bin_location VARCHAR(3));
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chair1', 'a good chair', 9031, 'A1');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chair2', 'an ok chair', 31, 'A2');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chair3', 'a super good chair', 331, 'A3');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chair4', 'not really a chair', 30, 'A4');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chair5', 'a good chair', 21, 'A5');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('grocery1', 'a good chair', 52, 'A6');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('grocery2', 'a good chair', 9031, 'A7');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('grocery3', 'a good chair', 9031, 'A8');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('grocery4', 'a good chair', 9031, 'A9');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('grocery5', 'a good chair', 9031, 'A10');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('paintbrush1', 'a good chair', 9031, 'B1');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('paintbrush2', 'a good chair', 9031, 'B2');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('paintbrush3', 'a good chair', 9031, 'B3');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('pbj1', 'a good chair', 9031, 'B4');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('pbj2', 'a good chair sandwich', 9031, 'B5');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('pbj3', 'a good chair', 9031, 'B6');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('pbj4', 'a good chair', 9031, 'B7');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('pbj5', 'a good chair', 9031, 'B8');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('water1', 'clean water', 9031, 'B9');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('water2', 'extra clean water', 9031, 'B10');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chaegaegir2', 'a good chair', 9031, 'C1');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chaegaegir2', 'a good chair', 9031, 'C2');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chagzxgir2', 'a good chair', 9031, 'C3');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chaihrhrar2', 'a good chair', 9031, 'C4');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chnandsair2', 'a good chair', 9031, 'C5');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chaijcjvair2', 'a good chair', 9031, 'C6');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chaobojafbfair2', 'a good chair', 9031, 'C7');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chaiorgoar2', 'a good chair', 9031, 'C8');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('water3', 'a good chair', 9031, 'C9');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('ceboak2', 'a good chair', 9031, 'C10');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('eoagkeaogae', 'a good chair', 9031, 'D1');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('geoageaogeni', 'a good chair', 9031, 'D2');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('water4', 'a good chair', 9031, 'D3');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('xzvizxviz', 'a good chair', 9031, 'D4');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('egageag', 'a good chair', 9031, 'D5');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chageageair2', 'a good chair', 9031, 'D6');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chazdgir2', 'random thing', 9031, 'D7');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chadgaadir2', 'a good chair', 9031, 'D8');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chazcbbzbir2', 'a good chair', 9031, 'D9');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('ctewtwetwethair2', 'a good chair', 9031, 'D10');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('cdgbdzbzbdhair2', 'a good chair', 9031, 'E1');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chabozkbzir2', 'a good chair', 9031, 'E2');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('water5', 'a good chair', 9031, 'E3');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chasgagsagasir2', 'a good chair', 9031, 'E4');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chainfndfsnr2', 'a good chair', 9031, 'E5');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chaoagokeair2', 'a good chair', 9031, 'E6');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('covzovozxv', 'a good chair', 9031, 'E7');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('cbozobkozr2', 'a good chair', 9031, 'E8');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('ccboxcoboxck', 'a good chair', 9031, 'E9');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('notagoodchair', 'a great chair', 9031, 'E10');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('cvzxov2', 'a good chair', 9031, 'F1');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chairaadadadgadadad2', 'a good chair', 9031, 'F2');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('charadaradaradair2', 'a good chair', 9031, 'F3');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('choekfaoefodir2', 'a good chair', 9031, 'F4');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('cheoakfoaeair2', 'a good chair', 9031, 'F5');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chaeafoeafir2', 'a good chair', 9031, 'F6');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('choefkaofkeaogair2', 'a good chair', 9031, 'F7');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chpwlafpaeofair2', 'a good chair', 9031, 'F8');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chpwalfpawflpxzlcair2', 'a good chair', 9031, 'F9');
INSERT INTO warehouseTable (product_name, description, stock_lvl, bin_location) VALUES('chaoeafojzfir9', 'a good chair', 9031, 'F10');
